### ISSUE TITLE
Add a google group, and gitter chat

### ISSUE THREAD

**Issue by criccomini** [debezium/debezium#20]
It would be good to have a Google group to ask questions in. This project looks really useful, but relatively nascent. Having ways to communicate will be helpful.

**Comment by rhauch** [comment]
Google Group is available at https://groups.google.com/forum/#!forum/debezium. We're already on Freenode IRC in #debezium, but open to alternatives.

**Comment by criccomini** [comment]
For chat, I'm selfish and would push for http://gitter.im. It integrates really well with Github. Your call, but that's my vote.

**Comment by emmanuelbernard** [comment]
A lot of the red hat folks have converged over HipChat for the Atlassian integration. Slack by some. But there is a huge war vs plain old IRC plus a transcript bot :)

**Comment by criccomini** [comment]
Haha yea. I currently have Hipchat, Slack, Google hangouts/gmail, Linkedin, Twitter. No FB@Work yet, and have gotten by without IRC, but guess I'll need to get it. :)

**Comment by criccomini** [comment]
Can you add the Google groups link to the README.md? (or I can send a PR)

**Comment by rhauch** [comment]
Go ahead and create a PR about the README. We can evaluate Gitter/HipChat further.

**Comment by criccomini** [comment]
Done! https://github.com/debezium/debezium/pull/22

**Comment by rhauch** [comment]
#22 has been merged, and we now have two Gitter rooms:

* https://gitter.im/debezium/user for general discussion and questions about using Debezium; and
* https://gitter.im/debezium/dev for more detailed discussion about developing/contributing to Debezium

I'll update the README with these links.

**Comment by rhauch** [comment]
#25 has been merged, so closing.
